version : '3.8'
services:
  playwright-test:
  image: playwright-test
  build:
    contenxt: .
    dockerfile: ./Dockerfile
  command: npm run test-ui
  volumes:
    - ./playwright-report/:/app/playwright-report
    - ./test-results/:/app/test-results
